# Generated by Django 5.2.1 on 2025-06-25 23:49

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('gst_details', models.CharField(blank=True, max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Designer', 'Designer'), ('Manager', 'Manager'), ('Production', 'Production')], default='Designer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_customers', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('depth_in', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('body_color', models.CharField(blank=True, max_length=40)),
                ('door_color', models.CharField(blank=True, max_length=40)),
                ('body_material', models.CharField(blank=True, max_length=120)),
                ('door_material', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Design', 'In Design'), ('In Production', 'In Production'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_designer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_projects', to='accounts.member')),
                ('assigned_production', models.ForeignKey(blank=True, limit_choices_to={'role': 'Production'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_projects', to='accounts.member')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_num', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to=accounts.models.production_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_images', to='accounts.projectdetail')),
            ],
            options={
                'ordering': ('image_num',),
                'unique_together': {('project', 'image_num')},
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_num', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to=accounts.models.drawings_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='accounts.projectdetail')),
            ],
            options={
                'ordering': ('drawing_num',),
                'unique_together': {('project', 'drawing_num')},
            },
        ),
    ]
