# Generated by Django 5.2.1 on 2025-05-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_verified',
        ),
    ]
