# Generated by Django 5.1.7 on 2025-06-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_emailotp_remove_admin_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.admin'),
        ),
    ]
