# Generated by Django 5.1.7 on 2025-06-15 06:00

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_ft', models.DecimalField(decimal_places=2, max_digits=7)),
                ('width_ft', models.DecimalField(decimal_places=2, max_digits=7)),
                ('depth_in', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('drawing1', models.ImageField(blank=True, null=True, upload_to=accounts.models.drawing_upload_path)),
                ('drawing2', models.ImageField(blank=True, null=True, upload_to=accounts.models.drawing_upload_path)),
                ('drawing3', models.ImageField(blank=True, null=True, upload_to=accounts.models.drawing_upload_path)),
                ('drawing4', models.ImageField(blank=True, null=True, upload_to=accounts.models.drawing_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='accounts.customer')),
                ('designer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member')),
            ],
        ),
    ]
