# Generated by Django 5.1.7 on 2025-06-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_file', models.FileField(upload_to='project_drawings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='accounts.projectdetail')),
            ],
        ),
    ]
