# Generated by Django 5.1.7 on 2025-06-16 03:51

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_projectdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='drawing1',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='drawing2',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='drawing3',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='drawing4',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='body_color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='body_material',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='door_color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='door_material',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='material_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='depth_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='length_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='width_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_num', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to=accounts.models.drawings_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='accounts.projectdetail')),
            ],
            options={
                'ordering': ('drawing_num',),
                'unique_together': {('project', 'drawing_num')},
            },
        ),
    ]
