# Generated by Django 5.1.7 on 2025-06-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_projectdetail_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
