# Generated by Django 5.1.7 on 2025-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_projectdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
