# Generated by Django 5.1.7 on 2025-06-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_projectdetail_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='accounts.customer'),
        ),
    ]
