# Generated by Django 5.1.7 on 2025-06-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_projectdetail_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='accounts.customer'),
        ),
    ]
