# Generated by Django 5.1.7 on 2025-06-19 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_projectdetail_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='assigned_designer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_projects', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='assigned_production',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Production'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_projects', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Design', 'In Design'), ('In Production', 'In Production'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
