# Generated by Django 5.1.7 on 2025-06-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_projectdetail_assigned_designer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='material_name',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
