# Generated by Django 5.1.7 on 2025-06-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_customer_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
