# Generated by Django 5.1.7 on 2025-06-20 01:22

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_projectdetail_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_num', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to=accounts.models.production_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_images', to='accounts.projectdetail')),
            ],
            options={
                'ordering': ('image_num',),
                'unique_together': {('project', 'image_num')},
            },
        ),
    ]
